server:
  port: 4545
  ssl:
    enabled: true
    key-store: etc/letsencrypt/archive/silas-ecomm.com:keystore.jks
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: javaKey

  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      suffix: ''
      file-date-format: ''

spring:
  application:
    name: demo

  profiles:
    active: spring.profiles.active@
    
logging:
  level:
    org:
      springframework:
        # web: DEBUG
        # security: DEBUG
        # beans: DEBUG
      hibernate: DEBUG

  file:
    name: myapplication.log
management:
  endpoints:
    jmx:
      exposure:
        include: none
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/ecomm_store
    username: root
    password: 30624003
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[use_sql_comments]": true
  devtools:
    restart:
      enabled: true
  jmx:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: ec2

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[use_sql_comments]": true




