server:
  port: 4545
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      suffix: ''
      file-date-format: ''

spring:

  application:
    name: demo

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecomm_store
    username: root
    password: 30624003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show_sql: true
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
         "[format_sql]": true
         "[use_sql_comments]": true

  devtools:
    restart:
      enabled: true

  jmx:
    enabled: false



        
# logging.config=src/main/resources/log4j2.xml
logging:
  level:
    org:
      springframework:
        web: debug
        hibernate: error
  file:
    name: myapplication.log


profiles:
    active: debug


management:
  endpoints:
    jmx:
      exposure:
        include: none

