name: Java CD with EC2

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Pull Docker Image
      run: sudo docker pull sheldrakecreator/ecommrepo:server
    - name: Delete Old Docker Container
      run: sudo docker rm -f ecommrepo-container || true
    - name: Run New Docker Container
      run: sudo docker run -d -p 4545:4545 --name ecommrepo-container sheldrakecreator/ecommrepo:server

  